### ISSUE TITLE
Ramp Tool: save list of surviving validators to disk  

### ISSUE THREAD

**Issue by mvines** [solana-labs/tour-de-sol#43]
At the end of a Ramp TPS, it would be very useful to have a single file that contains the list of validator identity pubkeys that survived each round.   Perhaps a simple yaml file is sufficent:
```yaml
round1:
  - pubkey1
  - pubkey2
  - pubkey3
round2:
  - pubkey1
  - pubkey2
```
